services:
    _defaults:
        autowire: true

    OxidEsales\DeveloperTools\Framework\Database\Command\ResetDatabaseCommand:
        tags:
            - { name: 'console.command', command: 'oe:database:reset' }
