services:
    _defaults:
        autowire: true

    OxidEsales\DeveloperTools\Framework\Database\Service\DropDatabaseServiceInterface:
        class: OxidEsales\DeveloperTools\Framework\Database\Service\DropDatabaseService
