services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\DeveloperTools\Framework\Database\Service\DropDatabaseServiceInterface:
        class: OxidEsales\DeveloperTools\Framework\Database\Service\DropDatabaseService