services:
    _defaults:
        autowire: true
        public: false

    OxidEsales\DeveloperTools\Framework\Theme\Command\ThemeActivateCommand:
        deprecated: 'This service is deprecated. See OxidEsales\EshopCommunity\Internal\Framework\Theme\Command\ThemeActivateCommand instead'
        class: OxidEsales\DeveloperTools\Framework\Theme\Command\ThemeActivateCommand
        tags:
            - { name: 'console.command', command: 'oe:theme:activate' }
